/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: "doc",
      label: "Tutorial Intro",
      id: 'intro'
    },
    {
      type: 'category',
      label: "Tutorial - Basics",
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "Create a Page",
          id: 'tutorial-basics/create-a-page'
        },
      ]
    },
    {
      type: 'category',
      label: "Tutorial - Extras",
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "Manage Docs Versions",
          id: 'tutorial-extras/manage-docs-versions'
        },
      ]
    }
  ],

  api: [
    {
      type: 'category',
      label: "API",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "API Index",
          id: 'api/api-index'
        }
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
